(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: Alignment Drills_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Sunday, 07 May 2023 at 18:53)

(This preprocessor is the default preprocessor used by FlatCAM.)
(It is made to work with MACH3 compatible motion controllers.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 0.5)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 25.0)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -2.5)

(Tools Offset: )
(Tool: 1 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 1.0)

(Z Toolchange: 5.0 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 5.0 mm)
(X,Y End: 0.0000, 0.0000 mm)
(Steps per circle: 64)
(Preprocessor Excellon: default)

(X range:    2.7500 ...   45.2500  mm)
(Y range:  -26.2000 ...   26.2500  mm)

(Spindle Speed: 1000 RPM)
G21
G90
G94

G01 F25.00

M5
G00 Z5.0000
T1
G00 X0.0000 Y0.0000                
M6
(MSG, Change to Tool Dia = 0.5000 ||| Total drills for tool T1 = 4)
M0
G00 Z5.0000

G01 F25.00
M03 S1000
G00 X3.0000 Y26.0000
G01 Z-2.5000
G01 Z0
G00 Z1.0000
G00 X45.0000 Y26.0000
G01 Z-2.5000
G01 Z0
G00 Z1.0000
G00 X45.0000 Y-25.9500
G01 Z-2.5000
G01 Z0
G00 Z1.0000
G00 X3.0000 Y-25.9500
G01 Z-2.5000
G01 Z0
G00 Z1.0000
M05
G00 Z5.00
G00 X0.0 Y0.0


