(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: PowerAndCommModule-PTH.drl_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Sunday, 07 May 2023 at 20:29)

(This preprocessor is the default preprocessor used by FlatCAM.)
(It is made to work with MACH3 compatible motion controllers.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 0.6)
(Tool: 2 -> Dia: 1.0)
(Tool: 3 -> Dia: 1.2)
(Tool: 4 -> Dia: 1.4)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 25.0)
(Tool: 2 -> Feedrate: 25.0)
(Tool: 3 -> Feedrate: 25.0)
(Tool: 4 -> Feedrate: 25.0)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)
(Tool: 2 -> Feedrate Rapids: 1500)
(Tool: 3 -> Feedrate Rapids: 1500)
(Tool: 4 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -2.5)
(Tool: 2 -> Z_Cut: -2.5)
(Tool: 3 -> Z_Cut: -2.5)
(Tool: 4 -> Z_Cut: -2.5)

(Tools Offset: )
(Tool: 4 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 1.0)
(Tool: 2 -> Z_Move: 1.0)
(Tool: 3 -> Z_Move: 1.0)
(Tool: 4 -> Z_Move: 1.0)

(Z Toolchange: 5.0 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 5.0 mm)
(X,Y End: 0.0000, 0.0000 mm)
(Steps per circle: 64)
(Preprocessor Excellon: default)

(X range:    5.2800 ...   42.0800  mm)
(Y range:  -24.1200 ...   21.5200  mm)

(Spindle Speed: 1000 RPM)
G21
G90
G94

G01 F25.00

M5
G00 Z5.0000
T4
G00 X0.0000 Y0.0000                
M6
(MSG, Change to Tool Dia = 1.4000 ||| Total drills for tool T4 = 6)
M0
G00 Z5.0000

G01 F25.00
M03 S1000
G00 X7.8700 Y-21.8800
G01 Z-2.5000
G01 Z0
G00 Z1.0000
G00 X7.8700 Y-16.8800
G01 Z-2.5000
G01 Z0
G00 Z1.0000
G00 X17.3600 Y20.8200
G01 Z-2.5000
G01 Z0
G00 Z1.0000
G00 X22.3600 Y20.8200
G01 Z-2.5000
G01 Z0
G00 Z1.0000
G00 X29.3900 Y20.8200
G01 Z-2.5000
G01 Z0
G00 Z1.0000
G00 X34.3900 Y20.8200
G01 Z-2.5000
G01 Z0
G00 Z1.0000
M05
G00 Z5.00
G00 X0.0 Y0.0


